# Exercicios Feitos em Aula

NOME1 = input("DIGITE O NOME DA PRIMEIRA PESSOA: ")
NASCIMENTO1 = int(input("\nDIGITE A DATA DE NASCIMENTO DA PRIMEIRA PESSOA: "))

NOME2 = input("\nDIGITE O NOME DA SEGUNDA PESSOA: ")
NASCIMENTO2 = int(input("\nDIGITE A DATA DE NASCIMENTO DA SEGUNDA PESSOA: "))

ANOATUAL = int(input("\nDIGITE O ANO ATUAL: "))

IDADEATUAL1 = ANOATUAL - NASCIMENTO1
IDADEATUAL2 = ANOATUAL - NASCIMENTO2

if NASCIMENTO1 < NASCIMENTO2:
    print("\n",NOME1,"TEM",IDADEATUAL1,"ANOS E É MAIS VELHO,","NASCEU EM",NASCIMENTO1)
elif IDADE1 == IDADE2:
    print("\n",NOME1," E ",NOME2," TEM A MESMA IDADE: ",IDADEATUAL1, "NASCERAM EM",NASCIMENTO2)
else:
    print("\n",NOME2,"TEM",IDADEATUAL2,"ANOS E É MAIS VELHO,","NASCEU EM",NASCIMENTO2)
print("\nFIM!")
