# Exercicio feito em aula

NOME1 = input("DIGITE O NOME DA PRIMEIRA PESSOA: ")
IDADE1 = int(input("DIGITE A IDADE DA DE: "+NOME1))

NOME2 = input("DIGITE O NOME DA SEGUNDA PESSOA: ")
IDADE2 = int(input("DIGITE A IDADE DE "+NOME2))

ANOATUAL = int(input("DIGITE O ANO ATUAL"))

NOME1_MAISVELHO = ANOATUAL - IDADE1
NOME2_MAISVELHO = ANOATUAL - IDADE2

if IDADE1 > IDADE2:
    print(NOME1,"É MAIS VELHO,TEM",IDADE1,"ANOS, NASCEU EM",NOME1_MAISVELHO)
elif IDADE1 == IDADE2:
    print(NOME1," E ",NOME2," TEM A MESMA IDADE", IDADE1,"NASCERAM EM ",NOME1_MAISVELHO)
else:
    print(NOME2,"É MAIS VELHO,TEM",IDADE2,"ANOS, NASCEU EM",NOME2_MAISVELHO)
    
print("\nFIM!")
